on: [push]

jobs:
  artillery-job:
    runs-on: ubuntu-latest
    name: Run Load Test
    steps:
    - uses: actions/checkout@v1
    - name: Artillery
      uses: SenorGrande/automated-artillery-action@feat/unique-report-name
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        artillery_path: 'index.yml'